name: news_c17_fri
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  google_fonts: ^6.3.2
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  loader_overlay: ^5.0.0
  injectable: ^2.7.1+4
  get_it: ^9.2.1
  connectivity_plus: ^7.0.0
  flutter_launcher_icons: ^0.14.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.12.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/helth.png"
  min_sdk_android: 21
